### Config File - This file contains the main settings for the debris flow simulation run
## Copy to  local_c1TifCfg.ini and set your parameters


[GENERAL]
# so far no general parameters to be set as debris flow option is fully implemented in com1DFA
# hence checkout the com1DFA_override section

[com1DFA_com1DFA_override]

#####
# PLEASE NOTE: these settings are untested and highly experimental. Use with caution!
#####

# use default com1DFA config as base configuration (True) and override following parameters
# if False and local_com1DFACfg is available use local
defaultConfig = True

#++++++++++++++++ Simulation type
# list of simulations that shall be performed (null, ent, res, entres, available (use all available input data))
simTypeList = available
# model type - only for file naming (dfa - dense flow avalanche)
modelType = dfa

#+++++++++++++ Output++++++++++++
# desired result Parameters (ppr, pft, pfv, pta, FT, FV, P, FM, Vx, Vy, Vz, TA, particles) - separated by |
resType = pft|pfv|ppr

#+++++++++Debris flow properties
# density of debris flow mixture [kg/m³]
# Override for density of fluid-solid mixture for debris flows
rho = 2000
# density of entrained debris [kg/m³]
# TODO adjusting
rhoEnt = 2000

#++++++++++++++++ Particles
# mass per particle (if MPPDIR is used) [kg]
massPerPart = 280000.

#+++++++++++++general start conditions: time dependent release
# if timeDependentRelease is True, provide the the timesteps, thickness and velocity
# for a releases in a csv-table in the REL folder
timeDependentRelease = True
# when checking if an already existing particle is within a release polygon
# (that would cause numerical instabilities and rise an error), one can decide to add a buffer
# around the polygon (0 means take strictly the points inside, a very small value
# will include the points located on the polygon line)
thresholdPointInRel = 0.01

#++++++++++++Time stepping parameters
# End time [s]
tEnd = 600

#++++++++++++Friction model
# add the friction using an explicit formulation (1)
# or use an implicit method (0)
explicitFriction = 0
# friction type. Available options are:
# Coulomb
# Voellmy
# spatialVoellmy
## Rheological models for debris-flow simulations
# OBrienAndJulien
# HerschelAndBulkley
# Bingham
# Please note that each type has their own/separate parameters:
# https://docs.avaframe.org/en/latest/theoryCom1DFA.html#friction-model
frictModel = Voellmy
#+++++++++++++Voellmy friction model
muvoellmy = 0.155
xsivoellmy = 200
#+++++++++++++Coulomb friction model
mucoulomb = 0.47
#+++++++++DEBRIS FLOW properties
# density of sediment [kg/m³]
rhoSediment = 2650
# mean sediment size [m]
## TODO  adjusting
sizeSediment = 0.001
# maximum concentration of sediment particles [m³/m³]
cvMaxSediment = 0.615
# volumetric sediment concentration [m³/m³]
cvSediment = 0.4
#++++++++++++++Parameter Rheological models
# Basically, there are two options for defining the yield shear stress, tauy,
# and the dynamic viscosity, eta:
# - set the values directly (default) or
# - compute them using the alpha and beta parameters (see documentation).
# Set the eta and tauy values to 0 if you want to use the option
# that computes eta and tauy using the alpha and beta parameters.
#++++++++++++O´Brien and Julien
# viscosity parameter
etaObrienAndJulien = 25
# set etaObrienAndJulien to 0 to compute eta from alpha1EtaObrienAndJulien and beta1EtaObrienAndJulien
alpha1EtaObrienAndJulien = 0.14
beta1EtaObrienAndJulien = 12.96
# yield shear stress parameter
tauyObrienAndJulien = 200
# set tauyObrienAndJulien to 0 to compute tauy from alpha2TauyObrienAndJulien and beta2TauyObrienAndJulien
alpha2TauyObrienAndJulien = 0.2511
beta2TauyObrienAndJulien = 16.7
# parameter, default value Takahashi (1978)
alphaObrienAndJulien = 0.01
#++++++++++++Herschel and Bulkley
# yield shear stress parameter
tauyHerschelAndBulkley = 200
# set tauyHerschelAndBulkley to 0 to compute tauy from alpha2TauyHerschelAndBulkley and beta2TauyHerschelAndBulkley
alpha2TauyHerschelAndBulkley = 0.2511
beta2TauyHerschelAndBulkley = 16.7
# consistency factor K
kHerschelAndBulkley = 25
# flow exponent
nHerschelAndBulkley = 2
#++++++++++++Bingham
# viscosity parameter
etaBingham = 200
# set etaBingham to 0 to compute eta from alpha1EtaBingham and beta1EtaBingham
alpha1EtaBingham = 0.2511
beta1EtaBingham = 16.7
# yield shear stress parameter
tauyBingham = 2000
# set tauyBingham to 0 to compute tauy from alpha2TauyBingham and beta2TauyBingham
alpha2TauyBingham = 1.613
beta2TauyBingham = 17.81

#++++++++++++ Entrainment Erosion Energy
# Used to determine speed loss via energy loss due to entrained mass
entEroEnergy = 5000

#++++++++++++ Deposition, Erosion and adaptive surface
# adapt the topography every time step
# activate with 1
# if adaptSfcStopped = 1: stopped particles (velocity = 0 or stopping criterion is reached)
# are deleted and saved in an additional dictionary (particles["stoppedParticles"])
adaptSfcStopped = 0
adaptSfcDetrainment = 0
adaptSfcEntrainment = 0
# only adapt topography if changing height in at least one cell is > thresholdAdaptSfc [m]
thresholdAdaptSfc = 0.1
# use the adapted topography as background in the report plots
adaptDemPlot = False
