### Config File - This file contains the main settings for the debris flow simulation run
## Copy to  local_c1TifCfg.ini and set your parameters


[GENERAL]
# so far no general parameters to be set as debris flow option is fully implemented in com1DFA
# hence checkout the com1DFA_override section

[com1DFA_com1DFA_override]

#####
# PLEASE NOTE: these settings are untested and highly experimental. Use with caution!
#####

# use default com1DFA config as base configuration (True) and override following parameters
# if False and local_com1DFACfg is available use local
defaultConfig = True

#++++++++++++++++ Simulation type
# list of simulations that shall be performed (null, ent, res, entres, available (use all available input data))
simTypeList = available
# model type - only for file naming (dfa - dense flow avalanche)
modelType = dfa

#+++++++++++++ Output++++++++++++
# desired result Parameters (ppr, pft, pfv, pta, FT, FV, P, FM, Vx, Vy, Vz, TA, particles) - separated by |
resType = pft|pfv|ppr

#+++++++++Debris flow properties
# density of debris flow mixture [kg/m³]
# Override for density of fluid-solid mixture for debris flows
rho = 2000
# density of entrained debris [kg/m³]
# TODO adjusting
rhoEnt = 2000

#++++++++++++++++ Particles
# mass per particle (if MPPDIR is used) [kg]
massPerPart = 280000.

#+++++++++++++general start conditions: time dependent release
# if timeDependentRelease is True, provide the the timesteps, thickness and velocity
# for a releases in a csv-table in the REL folder
timeDependentRelease = True
# when checking if an already existing particle is within a release polygon
# (that would cause numerical instabilities and rise an error), one can decide to add a buffer
# around the polygon (0 means take strictly the points inside, a very small value
# will include the points located on the polygon line)
thresholdPointInRel = 0.01

#++++++++++++Friction model
# add the friction using an explicit formulation (1)
# or use an implicit method (0)
explicitFriction = 0
# friction type. Available options are:
# samosAT - standard setup
# samosATSmall - setup for release volumes < 25k m³
# samosATMedium - setup for release volumes < 60k m³
# samosATAuto - chooses samosAT, samosATSmall or samosATMedium based on release volume and volClass
# Coulomb
# Voellmy
# VoellmyMinShear
# spatialVoellmy
# CoulombMinShear
# wetsnow
## Rheological models for debris-flow simulations
# OBrienAndJulien
# HerschelAndBulkley
# Ostwald
# Bingham
# Newton
# Please note that each type has their own/separate parameters:
# https://docs.avaframe.org/en/latest/theoryCom1DFA.html#friction-model
frictModel = Bingham
#+++++++++++++Voellmy friction model
muvoellmy = 0.155
xsivoellmy = 4000.
#+++++++++++++Coulomb friction model
mucoulomb = 0.155
#+++++++++DEBRIS FLOW properties
# density of sediment [kg/m³]
rhoSediment = 2650
# mean sediment size [m]
## TODO  adjusting
sizeSediment = 0.002
# maximum concentration of sediment particles [m³/m³]
cvMaxSediment = 0.615
# volumetric sediment concentration [m³/m³]
## TODO adjusting
cvSediment = 0.5
#++++++++++++++Parameter Rheological models
#++++++++++++O´Brien and Julien
# viscosity parameter
## TODO adjusting, default value O´Brien and Julien (1985)
alpha1EtaObrienAndJulien = 0.650
## TODO adjusting, default value O´Brien and Julien (1985)
beta1EtaObrienAndJulien = 16.81
# yield shear stress parameter
## TODO adjusting, default value O´Brien and Julien (1985)
alpha2TauyObrienAndJulien = 0.00886
 ## TODO adjusting, default value O´Brien and Julien (1985)
beta2TauyObrienAndJulien = 13.11
# parameter, default value Takahashi (1978)
alphaObrienAndJulien = 0.01
#++++++++++++Herschel and Bulkley
# viscosity parameter
## TODO adjusting, default value O´Brien and Julien (1985)
alpha1EtaHerschelAndBulkley = 0.650
 ## TODO adjusting, default value O´Brien and Julien (1985)
beta1EtaHerschelAndBulkley = 16.81
# yield shear stress parameter
 ## TODO adjusting, default value O´Brien and Julien (1985)
alpha2TauyHerschelAndBulkley = 0.00886
 ## TODO adjusting, default value O´Brien and Julien (1985)
beta2TauyHerschelAndBulkley = 13.11
# flow exponent
## TODO adjusting
nHerschelAndBulkley = 1.5
#++++++++++++Bingham
# viscosity parameter
## TODO adjusting, default value O´Brien and Julien (1985)
alpha1EtaBingham = 0.650
 ## TODO adjusting, default value O´Brien and Julien (1985)
beta1EtaBingham = 16.81
# yield shear stress parameter
 ## TODO adjusting, default value O´Brien and Julien (1985)
alpha2TauyBingham = 0.00886
 ## TODO adjusting, default value O´Brien and Julien (1985)
beta2TauyBingham = 13.11

#++++++++++++ Entrainment Erosion Energy
# Used to determine speed loss via energy loss due to entrained mass
entEroEnergy = 5000

#++++++++++++ Deposition, Erosion and adaptive surface
# adapt the topography every time step
# activate with 1
# if adaptSfcStopped = 1: stopped particles (velocity = 0 or stopping criterion is reached)
# are deleted and saved in an additional dictionary (particles["stoppedParticles"])
adaptSfcStopped = 0
adaptSfcDetrainment = 0
adaptSfcEntrainment = 0
# only adapt topography if changing height in at least one cell is > thresholdAdaptSfc [m]
thresholdAdaptSfc = 0.1
# use the adapted topography as background in the report plots
adaptDemPlot = False
