### Config File - This file contains the main settings for the rock avalanche simulation run
## Copy to  local_com6RockAvalancheCfg.ini and set your parameters


[GENERAL]


[com1DFA_com1DFA_override]

#####
# PLEASE NOTE: these settings are untested and highly experimental. Use with caution!
#####

# use default com1DFA config as base configuration (True) and override following parameters
# if False and local_com1DFACfg is available use local
defaultConfig = True

#++++++++++++++++ Simulation type
# list of simulations that shall be performed (null, ent, res, entres, available (use all available input data))
simTypeList = available
# model type - only for file naming (dfa - dense flow avalanche)
modelType = dfa

#+++++++++++++ Output++++++++++++
# desired result Parameters (ppr, pft, pfv, pta, FT, FV, P, FM, Vx, Vy, Vz, TA, particles) - separated by |
resType = pft|pfv|ppr

#+++++++++SNOW properties
# density of snow [kg/m³]
rho = 1500
# density of entrained snow [kg/m³]
rhoEnt = 2000
#+++++Release thickness++++
# True if release thickness should be read from shapefile file; if False - relTh read from ini file
relThFromShp = False
# read release thickness directly from file (relThFromShp needs to be False)
relThFromFile = False
# release thickness (only considered if relThFromShp=False) [m]
relTh = 0.3
#+++++Entrainment thickness++++
# True if entrainment thickness should be read from shapefile file; if False - entTh read from ini file
entThFromShp = False
# if a thickness value is missing for the entrainment feature in the provided shp file this value is used for all features [m]
entThIfMissingInShp = 0.3
# entrainment thickness (only considered if entThFromShp=False) [m]
entTh = 0.1

#++++++++++++Time stepping parameters
# fixed time step (also used as first time step when using CFL) [s]
dt = 0.1
# End time [s]
tEnd = 400
# to use a variable time step (time step depends on kernel radius)
sphKernelRadiusTimeStepping = False
# Upper time step limit coefficient if option sphKernelRadiusTimeStepping is chosen.
cMax = 0.02
# stopCriterion (based on massFlowing or kinEnergy)
stopCritType = kinEnergy
# if based on massFlowing, specify the velocity threshold for flowing mass [m/s]
uFlowingThreshold = 0.01
# stopCriterion (stops when massFlowing<0.01*peakMassFlowing or ke<0.01*pke)
stopCrit = 0.01

#+++++++++++++SPH parameters
# SPH gradient option
# 0) No pressure gradients computed
# 1) SamosAT style (no reprojection on the surface, dz = 0 and gz is used)
# 2) SamosAT done in the cartesian coord system (reprojection on the surface, dz != 0 and g3 is used)
# 3) SamosAT but done in the local coord system (will hopefully allow us to add the earth pressure coef)
# and this time reprojection on the surface, dz not 0 and g3 is used
sphOption = 3

#++++++++++++++++ Particles
# number of particles defined by: MPPDIR= mass per particle direct, MPPDH= mass per particles through release thickness,
# MPPKR= mass per particles through number of particles per kernel radius
massPerParticleDeterminationMethod = MPPDH
# mass per particle (if MPPDIR is used) [kg]
massPerPart = 280000.
# release thickness per particle (if MPPDH is used) [m]
deltaTh = 0.5

# splitting option
# either split particles based on mass (splitOption = 0)
# or split/merge in order to keep a constant number of particles per kernel radius(splitOption = 1)
splitOption = 1
# if splitOption=0
# threshold for splitting particles, split if: mPart > massPerPart x thresholdMassSplit
thresholdMassSplit = 1.5
# when splitting a particle, the new one is placed at a distance distSplitPart x rPart
distSplitPart = 0.41
# if splitOption=1
# in how many particles do we split
nSplit = 2
# coefficient ruling the splitting of particles. Split if the number of particles per sph kernel radius is smaller
# than cMinNPPK x nPPK
cMinNPPK = 0.25
# coefficient ruling the merging of particles. Merge if the number of particles per sph kernel radius is bigger
# than cMaxNPPK x nPPK
cMaxNPPK = 2.5
# stop splitting if the mass of the particles is lower than cMinMass x massPerPart
cMinMass = 0.25
# stop merging if the mass of the particles is bigger than cMaxnMass x massPerPart
cMaxnMass = 5

#+++++++++++++Mesh and interpolation
# interpolation option
# 3 Options available : -0: nearest neighbour interpolation
#                       -1: equal weights interpolation
#                       -2: bilinear interpolation
interpOption = 2
# minimum flow thickness [m]
hmin = 0.05
# remesh the input rasters or look for remeshed rasters
# expected mesh size [m]
meshCellSize = 5
# threshold under which no remeshing is done
meshCellSizeThreshold = 0.001
# clean DEMremeshed directory to ensure remeshing if chosen meshCellsize is different from rasters in Inputs/
cleanRemeshedRasters = True
# resize files read from Inputs/RASTERS to be resized to extent of DEM as resizeThreshold x meshCellSize
resizeThreshold = 3

# Normal computation on rectangular grid
# 4 triangles method        6 triangles method         8 triangles method
# +----U----UR---+---+--... +----+----+----+---+--... +----+----+----+---+--...
# |   /|\   |   /|          |   /| 2 /|   /|          |\ 2 | 3 /|   /|           Y
# |  / | \  |  / |          |  / |  / |  / |          | \  |  / |  / |           ^
# | /  |  \ | /  | /        | /  | /  | /  | /        |  \ | /  | /  | /         |
# |/ 1 | 2 \|/   |/         |/ 1 |/ 3 |/   |/         | 1 \|/ 4 |/   |/          |
# +----P----L----+---+--... +----*----+----+---+--... +----*----+----+----+--... +-----> X
# |\ 4 | 3 /|   /|          | 6 /| 4 /|   /|          | 8 /|\ 5 |   /|
# | \  |  / |  / |          |  / |  / |  / |          |  / | \  |  / |
# |  \ | /  | /  | /        | /  | /  | /  | /        | /  |  \ | /  | /
# |   \|/   |/   |/         |/ 5 |/   |/   |/         |/ 7 | 6 \|/   |/
# +----+----+----+---+--... +----+----+----+---+--... +----+----+----+---+--...
# |   /|   /|   /|          |   /|   /|   /|          |   /|   /|   /|
# 4 Options available : -1: simple cross product method (with the diagonals P-UR and U-L)
#                       -4: 4 triangles method
#                       -6: 6 triangles method
#                       -8: 8 triangles method
methodMeshNormal = 1

#+++++++++++++ Particle reprojection
# 0: project vertically on the dem
# 1: conserve traveled distance during reprojection
# 2: use samos method (something like an orthogonal reprojection)
# reprojection method used in the computeForceC function (used to find the estimated new particles position)
reprojMethodForce = 2
# reprojection method used in the updatePositionC function (used to reproject the particles after
# updating their position)
reprojMethodPosition = 2
# maximum number of iterations (for method 1 and 2 methods)
reprojectionIterations = 5
# if reprojMethod = 1, specify the stop criterion : stops when error<thresholdProjection*distance
thresholdProjection = 0.001

#+++++++++++++Flow model parameters+++++++++
# take curvature term into account in the gravity acceleration term for computing the friction force
# (and gradient if curvAccInGradient=1)
# 0 if deactivated, 1 if activated
curvAccInFriction = 1
# take curvature term into account in the tangential momentum equation
# 0 if deactivated, 1 if activated
curvAccInTangent = 0
# if curvAccInFriction=1, take curvature term into account in the pressure gradient (if curvAccInGradient=1)
curvAccInGradient = 0

#++++++++++++Friction model
# add the friction using an explicit formulation (1)
# or use an implicit method (0)
explicitFriction = 0
# friction type. Available options are:
# samosAT - standard setup
# samosATSmall - setup for release volumes < 25k m³
# samosATMedium - setup for release volumes < 60k m³
# samosATAuto - chooses samosAT, samosATSmall or samosATMedium based on release volume and volClass
# Coulomb
# Voellmy
# VoellmyMinShear
# spatialVoellmy
# CoulombMinShear
# wetsnow
# Please note that each type has their own/separate parameters:
# https://docs.avaframe.org/en/latest/theoryCom1DFA.html#friction-model
frictModel = Voellmy
#+++++++++++++SamosAT friction model - standard calibration (samosAT)
musamosat = 0.155
tau0samosat = 0
Rs0samosat = 0.222
kappasamosat = 0.43
Rsamosat = 0.05
Bsamosat = 4.13
#+++++++++++++Voellmy friction model 
# default values for single layer (Meyrat et al. 2023)
muvoellmy = 0.2
xsivoellmy = 200.
#++++++++++++spatialVoellmy friction model
# no parameters provided, mu and xi read from file located in avalancheDir/Inputs/RASTERS
# file name needs to be of format *_mu.asc and *_xi.asc both are required and same extent as DEM
# fields will be remeshed to match desired computational domain (DEM, meshCellSize) if extent is within resizeThreshold x meshCellSize meters
#+++++++++++++CoulombMinShear friction model
mucoulombminshear = 0.155
tau0coulombminshear = 70
#+++++++++++++Coulomb friction model
mucoulomb = 0.2

#++++++++++++ Resistance force parameters
# Choose one resistance model:
# cRes : F = - cRes *hEff * rho * A* u²; hEff = min(hRes,h) [cRes] = 1/m
# cResH : F = - cResH * rho * A* u², [cResH] =[]
ResistanceModel = cRes
# height of the obstacles [m]
hRes = 10
# resistance parameters for different models
cRes = 0.003
cResH = 0.003

#++++++++++++ Detrainment parameter
# Flag if snow detrainment at obstacles (in resistance area) is computed
# detrainment can be added to resistance force (DetAndRes = True) or computed solely (DetWithoutRes = True)
detrainment = False
detWithoutRes = False
# detrainment parameter defined by Feistl et al. (2014)
# value need to be refined
detK = 10

#++++++++++++ Entrainment Erosion Energy
# Used to determine speed loss via energy loss due to entrained mass
entEroEnergy = 5000
entShearResistance = 0
entDefResistance = 0

# which result parameters shall be included as plots in report,  - separated by |
plotFields = pfv|pft|FT
