### Config File - This file contains the main settings for the in2TopoHyd module run
## Copy to  local_in2TopoHydCfg.ini and set your parameters
# This file is part of DebrisFrame

[GENERAL]

#++++++++++++++++ Hydraulic Boundary Conditions
# Elevation steps in vertical direction to calclules the flow area
dElev = 0.1
# method how the flow velocity as initial condition is calculated
# currently only the method after Rickenmann (1999) is available
velType = rickenmann
# mean slope for the cross section in flow direction [m/m]
# optional; if left blank, the slope is computed automatically
slope = 

[EXPORTS]
# export cell centers along the release line as points in a csv-file; for plausability check
# True or False
exportCrossSectionCells = True

