[GENERAL]
name = Scenario1

# The user needs to declare a starting point of the simulation in X (easting) and Y (northing) coordinates.
# Those coordinates must lay within the applied digital terrain model and have to be defined in the same projection.
# Starting point can be a distinct change within the longitudinal flow-profile
# (significant change in slope gradient at fan apex) or obstacles forcing the debris flow to deposit.
# pyTopRunDF reacts sensitively to the starting point, which is why the program changes the starting point after each
# single flow path and randomly sets a new one in a buffer around the initial starting cell (default maximum buffer = 3 cells).
# However, the user might need to accomplish maybe several simulations to achieve plausible results.

# if coordinates are not provided, a release point needs to be provided in the Inputs/REL folder as shp file
xKoord =
yKoord =
energyHeight = 0.1

# The volume must correspond to the unit of length measurement used for the projection of the digital terrain input model.
# In the example the volume is given in m 3 .
volume = 4000

# The mobility coefficient k B is a dimensionless parameter
coefficient = 28

mcsmax = 500
numLoopSimulation = 100000
# Define the radius for random starting points to be defined; Default: 3 gridsizes.
randomRadius = 3
# Denominantor=100 to compute decay factor
denominator = 100
# Kernel matrix for diffusion algorithm
# The values are reshaped with the shape to the matrix. Values are separated with ","
kernelMatrixValues = 0.05, 0.1, 0.05, 0.1, 0.4, 0.1, 0.05, 0.1, 0.05
kernelMatrixShape = 3,3