# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test single python version

on:
  push:
    branches: [ master ]
    paths-ignore:
          - 'docs/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
          - 'docs/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true
    - name: Install dependencies
      run: |
        python -m pip install  --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install numpy 
        pip install setuptools
        pip install pytest_mock
    - name: Install avaframe
      run: |
        pip install avaframe
    - name: Install debrisframe
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pytest -ra --cov --cov-report=xml --cov-report lcov:cov.info --cov-config=.coveragerc
    - uses: qltysh/qlty-action/coverage@v1
      with:
        token: ${{secrets.QLTY_COVERAGE_TOKEN}}
        files: cov.info
